name: Publish client package

on:
  push:
    branches:
      - main
    paths:
      - 'src/Edc.Api.Client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['7.0.x']
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      
      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release
      
      - name: Create package
        run: dotnet pack ./src/Edc.Api.Client/ --configuration Release --no-build
      
      - name: Publish package
        run: dotnet nuget push "src/Edc.Api.Client/bin/Release/*.nupkg" -k ${{ secrets.NUGET_EDC_SERVICE_TOKEN }} -s https://api.nuget.org/v3/index.json
        